### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by nirtamir2** [ahmetsait/toolgit#1]
I'm using MacOS. Unfortunately, I was unable to install toolgit. The command `git config set --append --global include.path ~/dotfiles/config/toolgit-main/aliases.ini` appears to be invalid.

To help me install toolgit correctly, could you please provide a Brew recipe or better installation instructions?

**Comment by ahmetsait** [comment]
The command works with Git v2.47.0 and is equivalent to adding the following lines into your `~/.gitconfig`:
```ini
[include]
	path = ~/dotfiles/config/toolgit-main/aliases.ini
```

**Comment by nirtamir2** [comment]
Thanks! The issue was that I used an older git version. 
I eventually move those scripts to my .bit folder (into path) and the aliases to `.gitconfig`
BTW - as a prerequisite I had to install `gnu-getopt` (and is still did not work with my MacOS but I didn't care about this script that much)
